name: Android

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.15
      - run: npm install -g @ionic/cli
      - run: npm install
      - run: yarn build
      - run: yarn init:android
      - run: yarn build:android

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

      - name: Publish to IPFS and WNS
        run: |
          set -e
          cd cli-app
          yarn && yarn build
          node publish-apk.js
          node register-apk.js
